services:
  disc-survey:
    build: 
      dockerfile: Dockerfile
    hostname: disc-web
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/home
    networks:
      - network-aaw

networks:
  network-aaw:
    driver: bridge
